name: Deploy To Google Cloud

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-deploy-${{ github.ref }}-1
  cancel-in-progress: true

env:
  GOOGLE_PROJECT: gynger-staging-344901
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  STRIPE_KEY: 'pk_test_51JAg6BK8ZYhlYrFtn5B5rmbQmemeAEJda5uJeLJqyoCF5vLHteEoymDmL2C7JXt6A9G8wHthcmXjUeubEsZVU8fY00XkTa0p3U'
  ALLOY_KEY: 'd11a3437-4031-4798-bdce-c41c2124b3a4'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npx eslint "src/**/*.ts*"
      - run: npm run build
  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    outputs:
      env_url: ${{ steps.set-env-url.outputs.env_url }}
    steps:
      - name: Downcase branch
        run: echo "BRANCH_NAME=${BRANCH_NAME,,}" >>${GITHUB_ENV}

      - name: Extract Ticket Number
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: extract_ticket_number
        with:
          text: ${{ env.BRANCH_NAME }}
          regex: '[gG][yY][nN]-[0-9]{4,6}'

      - name: Set and show ticket number
        run: |
          if ${{steps.extract_ticket_number.outputs.match != '' }}; then
            echo "JIRA_TICKET_NUMBER=${{steps.extract_ticket_number.outputs.match}}" >>${GITHUB_ENV}
          else
            echo "JIRA_TICKET_NUMBER=${{env.BRANCH_NAME}}" >>${GITHUB_ENV}
          fi

      - uses: actions/checkout@v3
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.STAGING_GCP_SA_KEY }}
      - name: Set Graphql Domain
        run: |
          gcloud run services list
          if gcloud run services list | grep -i -q backend-${{ env.JIRA_TICKET_NUMBER }}; then
            echo "GRAPHQL_DOMAIN=https://backend-${{ env.JIRA_TICKET_NUMBER }}-wappznbt3q-uc.a.run.app/graphql" >>${GITHUB_ENV}
          else
            echo "GRAPHQL_DOMAIN=https://staging.api.gynger.io/graphql" >>${GITHUB_ENV}
          fi
      - name: Set Vendor Graphql Domain
        run: |
          gcloud run services list
          if gcloud run services list | grep -i -q vendor-${{ env.JIRA_TICKET_NUMBER }}; then
            echo "VENDOR_GRAPHQL_DOMAIN=https://vendor-${{ env.JIRA_TICKET_NUMBER }}-wappznbt3q-uc.a.run.app/graphql" >>${GITHUB_ENV}
          else
            echo "VENDOR_GRAPHQL_DOMAIN=https://vendor-api-wappznbt3q-uc.a.run.app/graphql" >>${GITHUB_ENV}
          fi
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags: gcr.io/${{ env.GOOGLE_PROJECT }}/gynger-ale:${{ env.JIRA_TICKET_NUMBER }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          build-args: |
            REACT_APP_GRAPHQL_DOMAIN=${{ env.GRAPHQL_DOMAIN }}
            REACT_APP_VENDOR_GRAPHQL_DOMAIN=${{ env.VENDOR_GRAPHQL_DOMAIN }}
            REACT_APP_ENVIRONMENT=staging
            REACT_APP_ALLOY_KEY=${{ env.ALLOY_KEY }}
            REACT_APP_STRIPE_KEY=${{ env.STRIPE_KEY }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Deploy image to cloud run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: frontend-${{ env.JIRA_TICKET_NUMBER }}
          image: 'gcr.io/${{ env.GOOGLE_PROJECT }}/gynger-ale:${{ env.JIRA_TICKET_NUMBER }}'
      - name: Make Service Public
        run: |
          gcloud run services add-iam-policy-binding frontend-${{ env.JIRA_TICKET_NUMBER }} \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region="us-central1"
      - name: Add comment in ticket with env url
        run: |
          curl -X POST -H 'Content-type: application/json' \
           --data '{"issues":["${{ env.JIRA_TICKET_NUMBER }}"], "data":{"envUrl":"https://frontend-${{ env.JIRA_TICKET_NUMBER }}-wappznbt3q-uc.a.run.app"}}' \
               https://automation.atlassian.com/pro/hooks/cc33fa7198d0977f88861f078f4f72481af76d51

      - name: Comment on Github issue with custom env link
        if: github.run_number == 1
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Env url: https://frontend-${{ env.JIRA_TICKET_NUMBER }}-wappznbt3q-uc.a.run.app'
            })

      - id: set-env-url
        run: echo "env_url='https://frontend-${{ env.JIRA_TICKET_NUMBER }}-wappznbt3q-uc.a.run.app'" >> $GITHUB_OUTPUT

  test:
    needs: deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      REACT_APP_E2E_BASE_URL: ${{ needs.deploy.outputs.env_url }}
      REACT_APP_E2E_EMAIL: ${{ vars.REACT_APP_E2E_EMAIL }}
      REACT_APP_E2E_PASSWORD: ${{ vars.REACT_APP_E2E_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Run Playwright tests
        id: test-result
        run: REACT_APP_E2E_BASE_URL=${{ env.REACT_APP_E2E_BASE_URL }} && npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
