name: CI + CD

on:
  push:
    branches: [ main, staging ]
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'


  DeployDev:
    name: Deploy to Dev
    if: ${{ github.event_name == 'pull_request' && !(contains(github.ref, 'main') || contains(github.ref, 'staging')) }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://custom-env-app.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployStaging:
    name: Deploy to Staging
    if: ${{ github.event_name == 'push' && contains(github.ref, 'staging')  }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test-staging-env.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployProd:
    name: Deploy to Production
    if: ${{ github.event_name == 'push' && contains(github.ref, 'main') }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
