name: release

on:
  release:
    types: [published]

concurrency:
  group: ci-deploy-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.app.myapp.com'
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
