name: release

on:
  release:
    types: [published]

jobs:
  Release:
    name: Release latest to Production
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.app.myapp.com'
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

  DeployProd:
    name: Deploy to Production
    if: ${{ github.event_name == 'push' && contains(github.ref, 'main') }}
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.app.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
