name: Remove Google Cloud Run

on:
  pull_request:
    types: [closed]

env:
  GOOGLE_PROJECT: gynger-staging-344901
  gcp-cloud-sql-instance: gynger-database-instance
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  gcloud:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Downcase branch
        run: echo "BRANCH_NAME=${BRANCH_NAME,,}" >>${GITHUB_ENV}

      - name: Extract Ticket Number
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: extract_ticket_number
        with:
          text: ${{ env.BRANCH_NAME }}
          regex: '[gG][yY][nN]-[0-9]{4,6}'

      - name: Set and show ticket number
        run: |
          if ${{steps.extract_ticket_number.outputs.match != '' }}; then
            echo "JIRA_TICKET_NUMBER=${{steps.extract_ticket_number.outputs.match}}" >>${GITHUB_ENV}
          else
            echo "JIRA_TICKET_NUMBER=${{env.BRANCH_NAME}}" >>${GITHUB_ENV}
          fi

      - uses: actions/checkout@v3
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.STAGING_GCP_SA_KEY }}
      - name: Delete cloud service
        run: |
          gcloud run services delete frontend-${{ env.JIRA_TICKET_NUMBER }} --quiet --region="us-central1"
