on:
  pull_request:
    types: [ opened, closed ]
  pull_request_review:
    types: [ submitted ]
  workflow_dispatch:

concurrency:
  group: ci-transition-ticket-${{ github.ref }}-1
  cancel-in-progress: true

name: Transition JIRA ticket
env:
  regex: "gyn-\\d+"
  BRANCH_NAME: ${{ github.event.pull_request.head.ref || github.head.ref || github.head_ref  || github.ref_name }}

jobs:
  transition-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Extract Ticket Number
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: extract_ticket_number
        with:
          text: ${{ env.BRANCH_NAME }}
          regex: '[gG][yY][nN]-[0-9]{4,6}'

      - name: Set and show ticket number
        run: |
          if ${{steps.extract_ticket_number.outputs.match != '' }}; then
            echo "JIRA_TICKET_NUMBER=${{steps.extract_ticket_number.outputs.match}}" >>${GITHUB_ENV}
          else
            echo "JIRA_TICKET_NUMBER=${{env.BRANCH_NAME}}" >>${GITHUB_ENV}
          fi

      - name: Transition to [READY FOR CR]
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"issues":["${{env.JIRA_TICKET_NUMBER}}"]}' \
              https://automation.atlassian.com/pro/hooks/10ec22b97191fc5ca769fa8dbfa2e35d7d71bc0b

      - name: Transition to [READY FOR QA]
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"issues":["${{env.JIRA_TICKET_NUMBER}}"]}' \
              https://automation.atlassian.com/pro/hooks/20d7525c344df24bf43c4cf40e26308d41ec067d

      - name: Transition to [DOING]
        if: github.event_name == 'pull_request_review' && github.event.review.state != 'approved'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"issues":["${{env.JIRA_TICKET_NUMBER}}"]}' \
              https://automation.atlassian.com/pro/hooks/042ca644ceca6fc6a7328cadeeaec27d5aa29ab1

      - name: Transition to [DEPLOYED TO STAGING]
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"issues":["${{env.JIRA_TICKET_NUMBER}}"]}' \
              https://automation.atlassian.com/pro/hooks/6c2a3d38d843c4eba2e94edc4e0835a979770590
